In [1]:
# importing packages
import numpy as np
import pandas as pd
from glob import glob
import matplotlib.pyplot as plt
import seaborn as sns
import os

### Decompressing Zipped Data with GunZip in Terminal

gunzip name.of.file.gz

Or

gunzip *

In [2]:
# accessing zipped files
csv_files = glob("zippedData/*.csv")
csv_files

['zippedData/tmdb.movies.csv',
 'zippedData/imdb.title.crew.csv',
 'zippedData/tn.movie_budgets.csv',
 'zippedData/imdb.title.ratings.csv',
 'zippedData/imdb.name.basics.csv',
 'zippedData/imdb.title.principals.csv',
 'zippedData/imdb.title.akas.csv',
 'zippedData/bom.movie_gross.csv',
 'zippedData/imdb.title.basics.csv']

In [3]:
# creating a dictionary for the files
given_files_dict = {}
for given_file in csv_files:
    given_file_cleaned = os.path.basename(given_file).replace(".csv", "").replace(".", "_")
    given_file_df = pd.read_csv(given_file, index_col = 0)
    given_files_dict[given_file_cleaned] = given_file_df

In [4]:
# testing dictionary
given_files_dict.keys()

dict_keys(['tmdb_movies', 'imdb_title_crew', 'tn_movie_budgets', 'imdb_title_ratings', 'imdb_name_basics', 'imdb_title_principals', 'imdb_title_akas', 'bom_movie_gross', 'imdb_title_basics'])

# Looking at my different dataframes below.

# tmdb_movies

In [5]:
# just looking at the dataframes, this process will be repeated below.
given_files_dict['tmdb_movies']

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186
...,...,...,...,...,...,...,...,...,...
26512,"[27, 18]",488143,en,Laboratory Conditions,0.600,2018-10-13,Laboratory Conditions,0.0,1
26513,"[18, 53]",485975,en,_EXHIBIT_84xxx_,0.600,2018-05-01,_EXHIBIT_84xxx_,0.0,1
26514,"[14, 28, 12]",381231,en,The Last One,0.600,2018-10-01,The Last One,0.0,1
26515,"[10751, 12, 28]",366854,en,Trailer Made,0.600,2018-06-22,Trailer Made,0.0,1
26516,"[53, 27]",309885,en,The Church,0.600,2018-10-05,The Church,0.0,1

In [6]:
given_files_dict['tmdb_movies'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26517 entries, 0 to 26516
Data columns (total 9 columns):
genre_ids            26517 non-null object
id                   26517 non-null int64
original_language    26517 non-null object
original_title       26517 non-null object
popularity           26517 non-null float64
release_date         26517 non-null object
title                26517 non-null object
vote_average         26517 non-null float64
vote_count           26517 non-null int64
dtypes: float64(2), int64(2), object(5)
memory usage: 2.0+ MB

In [7]:
given_files_dict['tmdb_movies'].isna().sum()

genre_ids            0
id                   0
original_language    0
original_title       0
popularity           0
release_date         0
title                0
vote_average         0
vote_count           0
dtype: int64

# imbd_title_crew

In [8]:
given_files_dict['imdb_title_crew']

                               directors              writers
tconst
tt0285252                      nm0899854            nm0899854
tt0438973                            NaN  nm0175726,nm1802864
tt0462036                      nm1940585            nm1940585
tt0835418                      nm0151540  nm0310087,nm0841532
tt0878654  nm0089502,nm2291498,nm2292011            nm0284943
...                                  ...                  ...
tt8999974                     nm10122357           nm10122357
tt9001390                      nm6711477            nm6711477
tt9001494          nm10123242,nm10123248                  NaN
tt9004986                      nm4993825            nm4993825
tt9010172                            NaN            nm8352242

[146144 rows x 2 columns]

In [9]:
given_files_dict['imdb_title_crew'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 146144 entries, tt0285252 to tt9010172
Data columns (total 2 columns):
directors    140417 non-null object
writers      110261 non-null object
dtypes: object(2)
memory usage: 3.3+ MB

In [10]:
given_files_dict['imdb_title_crew'].isna().sum()

directors     5727
writers      35883
dtype: int64

# tn_movie_budgets

In [11]:
given_files_dict['tn_movie_budgets']

,release_date,movie,production_budget,domestic_gross,worldwide_gross
id,,,,,
1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...,...
78,"Dec 31, 2018",Red 11,"$7,000",$0,$0
79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [12]:
given_files_dict['tn_movie_budgets'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5782 entries, 1 to 82
Data columns (total 5 columns):
release_date         5782 non-null object
movie                5782 non-null object
production_budget    5782 non-null object
domestic_gross       5782 non-null object
worldwide_gross      5782 non-null object
dtypes: object(5)
memory usage: 271.0+ KB

In [13]:
given_files_dict['tn_movie_budgets'].isna().sum()

release_date         0
movie                0
production_budget    0
domestic_gross       0
worldwide_gross      0
dtype: int64

# imdb_title_ratings

In [14]:
given_files_dict['imdb_title_ratings']

            averagerating  numvotes
tconst
tt10356526            8.3        31
tt10384606            8.9       559
tt1042974             6.4        20
tt1043726             4.2     50352
tt1060240             6.5        21
...                   ...       ...
tt9805820             8.1        25
tt9844256             7.5        24
tt9851050             4.7        14
tt9886934             7.0         5
tt9894098             6.3       128

[73856 rows x 2 columns]

In [15]:
given_files_dict['imdb_title_ratings'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 73856 entries, tt10356526 to tt9894098
Data columns (total 2 columns):
averagerating    73856 non-null float64
numvotes         73856 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.7+ MB

In [16]:
given_files_dict['imdb_title_ratings'].isna().sum()

averagerating    0
numvotes         0
dtype: int64

# imdb_name_basics

In [17]:
given_files_dict['imdb_name_basics']

,primary_name,birth_year,death_year,primary_profession,known_for_titles
nconst,,,,,
nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer","tt0837562,tt2398241,tt0844471,tt0118553"
nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department","tt0896534,tt6791238,tt0287072,tt1682940"
nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer","tt1470654,tt0363631,tt0104030,tt0102898"
nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department","tt0114371,tt2004304,tt1618448,tt1224387"
nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator","tt0452644,tt0452692,tt3458030,tt2178256"
...,...,...,...,...,...
nm9990381,Susan Grobes,NaN,NaN,actress,NaN
nm9990690,Joo Yeon So,NaN,NaN,actress,"tt9090932,tt8737130"
nm9991320,Madeline Smith,NaN,NaN,actress,"tt8734436,tt9615610"
nm9991786,Michelle Modigliani,NaN,NaN,producer,NaN
nm9993380,Pegasus Envoyé,NaN,NaN,"director,actor,writer",tt8743182

In [18]:
given_files_dict['imdb_name_basics'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 606648 entries, nm0061671 to nm9993380
Data columns (total 5 columns):
primary_name          606648 non-null object
birth_year            82736 non-null float64
death_year            6783 non-null float64
primary_profession    555308 non-null object
known_for_titles      576444 non-null object
dtypes: float64(2), object(3)
memory usage: 27.8+ MB

In [19]:
given_files_dict['imdb_name_basics'].isna().sum()

primary_name               0
birth_year            523912
death_year            599865
primary_profession     51340
known_for_titles       30204
dtype: int64

# imdb_title_principles

In [20]:
given_files_dict['imdb_title_principals']

           ordering      nconst  category       job            characters
tconst
tt0111414         1   nm0246005     actor       NaN           ["The Man"]
tt0111414         2   nm0398271  director       NaN                   NaN
tt0111414         3   nm3739909  producer  producer                   NaN
tt0323808        10   nm0059247    editor       NaN                   NaN
tt0323808         1   nm3579312   actress       NaN      ["Beth Boothby"]
...             ...         ...       ...       ...                   ...
tt9692684         1   nm0186469     actor       NaN  ["Ebenezer Scrooge"]
tt9692684         2   nm4929530      self       NaN   ["Herself","Regan"]
tt9692684         3  nm10441594  director       NaN                   NaN
tt9692684         4   nm6009913    writer    writer                   NaN
tt9692684         5  nm10441595  producer  producer                   NaN

[1028186 rows x 5 columns]

In [21]:
given_files_dict['imdb_title_principals'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1028186 entries, tt0111414 to tt9692684
Data columns (total 5 columns):
ordering      1028186 non-null int64
nconst        1028186 non-null object
category      1028186 non-null object
job           177684 non-null object
characters    393360 non-null object
dtypes: int64(1), object(4)
memory usage: 47.1+ MB

In [22]:
given_files_dict['imdb_title_principals'].isna().sum()

ordering           0
nconst             0
category           0
job           850502
characters    634826
dtype: int64

# imdb_title_akas

In [23]:
given_files_dict['imdb_title_akas']

,ordering,title,region,language,types,attributes,is_original_title
title_id,,,,,,,
tt0369610,10,Джурасик свят,BG,bg,NaN,NaN,0.0
tt0369610,11,Jurashikku warudo,JP,NaN,imdbDisplay,NaN,0.0
tt0369610,12,Jurassic World: O Mundo dos Dinossauros,BR,NaN,imdbDisplay,NaN,0.0
tt0369610,13,O Mundo dos Dinossauros,BR,NaN,NaN,short title,0.0
tt0369610,14,Jurassic World,FR,NaN,imdbDisplay,NaN,0.0
...,...,...,...,...,...,...,...
tt9827784,2,Sayonara kuchibiru,NaN,NaN,original,NaN,1.0
tt9827784,3,Farewell Song,XWW,en,imdbDisplay,NaN,0.0
tt9880178,1,La atención,NaN,NaN,original,NaN,1.0
tt9880178,2,La atención,ES,NaN,NaN,NaN,0.0
tt9880178,3,The Attention,XWW,en,imdbDisplay,NaN,0.0

In [24]:
given_files_dict['imdb_title_akas'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 331703 entries, tt0369610 to tt9880178
Data columns (total 7 columns):
ordering             331703 non-null int64
title                331703 non-null object
region               278410 non-null object
language             41715 non-null object
types                168447 non-null object
attributes           14925 non-null object
is_original_title    331678 non-null float64
dtypes: float64(1), int64(1), object(5)
memory usage: 20.2+ MB

In [25]:
given_files_dict['imdb_title_akas'].isna().sum()

ordering                  0
title                     0
region                53293
language             289988
types                163256
attributes           316778
is_original_title        25
dtype: int64

# bom_movie_gross

In [26]:
given_files_dict['bom_movie_gross']

,studio,domestic_gross,foreign_gross,year
title,,,,
Toy Story 3,BV,415000000.0,652000000,2010
Alice in Wonderland (2010),BV,334200000.0,691300000,2010
Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
Inception,WB,292600000.0,535700000,2010
Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...
The Quake,Magn.,6200.0,NaN,2018
Edward II (2018 re-release),FM,4800.0,NaN,2018
El Pacto,Sony,2500.0,NaN,2018
The Swan,Synergetic,2400.0,NaN,2018
An Actor Prepares,Grav.,1700.0,NaN,2018

In [27]:
given_files_dict['bom_movie_gross'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 3387 entries, Toy Story 3 to An Actor Prepares
Data columns (total 4 columns):
studio            3382 non-null object
domestic_gross    3359 non-null float64
foreign_gross     2037 non-null object
year              3387 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 132.3+ KB

In [28]:
given_files_dict['bom_movie_gross'].isna().sum()

studio               5
domestic_gross      28
foreign_gross     1350
year                 0
dtype: int64

# imdb_title_basics

In [29]:
given_files_dict['imdb_title_basics']

,primary_title,original_title,start_year,runtime_minutes,genres
tconst,,,,,
tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...
tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
tt9916730,6 Gunn,6 Gunn,2017,116.0,NaN
tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [30]:
given_files_dict['imdb_title_basics'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 146144 entries, tt0063540 to tt9916754
Data columns (total 5 columns):
primary_title      146144 non-null object
original_title     146123 non-null object
start_year         146144 non-null int64
runtime_minutes    114405 non-null float64
genres             140736 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 6.7+ MB

In [31]:
given_files_dict['imdb_title_basics'].isna().sum()

primary_title          0
original_title        21
start_year             0
runtime_minutes    31739
genres              5408
dtype: int64

# shortcuts for reading the files

In [32]:
# creating shortcuts for all of the files
tmdb_movies = pd.read_csv('./zippedData/imdb.title.basics.csv')
imdb_title_crew = pd.read_csv('./zippedData/imdb.title.crew.csv')
tn_movie_budgets = pd.read_csv('./zippedData/tn.movie_budgets.csv')
imdb_title_ratings = pd.read_csv('./zippedData/imdb.title.ratings.csv')
imdb_name_basics = pd.read_csv('./zippedData/imdb.name.basics.csv')
imdb_title_principals = pd.read_csv('./zippedData/imdb.title.principals.csv')
imdb_title_akas = pd.read_csv('./zippedData/imdb.title.akas.csv')
bom_movie_gross = pd.read_csv('./zippedData/bom.movie_gross.csv')
imdb_title_basics = pd.read_csv('./zippedData/imdb.title.basics.csv')